name: diabetes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - loguru
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - pip:
    - raiwidgets
    - interpret-community
    - cookiecutter